### PR TITLE
Write directions on forking and keeping remotes in sync

### PR DESCRIPTION
**Pull request by mattstauffer**
I'm perfectly open to the suggestion this should A) just be a blog post we link, or B) be in a different file. Any thoughts?

### CODE REVIEW

**Comment by mattstauffer** [comment]
Preview:

screnshot

**Comment by nhuntwalker** [comment]
Note that the commit message could (and probably should) reference an issue that it resolves

**Review by nhuntwalker — COMMENTED** [review]
No real changes to make. Just note that commit messages could (and probably should) reference an issue that the commit itself resolves (or at least starts to address)

**Comment by mattstauffer** [comment]
@nhuntwalker You're absolutely right--thanks! I'll update it.

**Pull request merged**
